---
- name: create webapps root directory
  file:
    path: '{{ webapps_root_dir }}'
    state: directory
    setype: _default

- name: configure flatpak.org
  include: flatpak.yml
  tags:
    - flatpak

- name: configure flathub.org
  include: flathub.yml
  tags:
    - flathub

- name: configure nginx http servers
  include: nginx-http.yml
  tags:
    - nginx
    - dehydrated

- name: ensure nginx is running and run dehydrated
  meta: flush_handlers
  tags:
    - dehydrated
    - nginx

- name: configure nginx https servers
  include: nginx-https.yml
  tags:
    - nginx
