---
- name: install nginx conf.d/flatpak.conf
  template:
    src: nginx/conf.d/flatpak.conf
    dest: /etc/nginx/conf.d/flatpak.conf
  notify:
    - reload nginx

- name: install nginx conf.d/flathub.conf
  template:
    src: nginx/conf.d/flathub.conf
    dest: /etc/nginx/conf.d/flathub.conf
  notify:
    - reload nginx
