- name: configure nginx
  include: nginx.yml
  tags:
   - nginx

- name: set up certsync from front
  include: certsync.yml
  tags:
   - certsync

- name: ensure nginx is running and run dehydrated
  meta: flush_handlers
  tags:
   - dehydrated
   - nginx

- name: deploy nginx conf.d/ssl.conf
  template:
    src: nginx-conf.d-ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  notify:
   - reload nginx
  tags:
   - dehydrated
   - nginx

- name: deploy nginx conf.d/dl-ssl.conf
  template:
    src: nginx-conf.d-dl-ssl.conf.j2
    dest: /etc/nginx/conf.d/dl-ssl.conf
  notify:
   - reload nginx
  tags:
   - certsync
   - nginx

- name: deploy nginx conf.d/webroot-ssl.conf
  template:
    src: nginx-conf.d-webroot-ssl.conf.j2
    dest: /etc/nginx/conf.d/webroot-ssl.conf
  notify:
   - reload nginx
  tags:
   - certsync
   - nginx

- name: deploy nginx conf.d/flatpak-ssl.conf
  template:
    src: nginx-conf.d-flatpak-ssl.conf.j2
    dest: /etc/nginx/conf.d/flatpak-ssl.conf
  notify:
   - reload nginx
  tags:
   - certsync
   - nginx
