---
- name: set up certsync from front
  include: certsync.yml
  tags:
   - certsync

- name: configure nginx
  include: nginx.yml
  tags:
   - nginx

- name: ensure nginx is running and run dehydrated
  meta: flush_handlers
  tags:
   - dehydrated
   - nginx
