---
postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib
  - postgresql-devel
  - python3-psycopg2

postgresql_version: "9.2"
postgresql_data_dir: "/var/lib/pgsql/data"
postgresql_bin_path: "/usr/bin"
postgresql_config_path: "/var/lib/pgsql/data"
postgresql_daemon: postgresql
