---
postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2

postgresql_data_dir: "/var/lib/postgresql/10/main"
postgresql_bin_path: "/usr/lib/postgresql/10/bin"
postgresql_config_path: "/etc/postgresql/10/main"
postgresql_daemon: postgresql
