---
dependencies:
  - base
  - postgres
  - role: nginx
    tags:
      - repo-manager
      - repo-manager_nginx
  - role: dehydrated
    vars:
      dehydrated_domains:
        - '{{ repo_manager_domain }}'
    tags:
      - repo-manager
      - repo-manager_dehydrated
