- name: Ensure sources parent dir is readable by nginx
  file:
    path: "{{ sources_parent_dir }}"
    state: directory
    mode: 0775

- name: Create sources dir
  file:
    path: "{{ sources_dir }}"
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_user }}"
    state: directory
    mode: 0775

- name: install nginx conf.d/sources.conf
  template:
    src: nginx-conf.d-sources.conf.j2
    dest: /etc/nginx/conf.d/sources.conf
    mode: 0644
  notify:
   - reload nginx
  tags:
    - sources_nginx

- name: ensure nginx is running and dehydrated run to obtain certs
  meta: flush_handlers
  tags:
    - sources_dehydrated
    - sources_nginx

- name: install nginx conf.d/sources-ssl.conf
  template:
    src: nginx-conf.d-sources-ssl.conf.j2
    dest: /etc/nginx/conf.d/sources-ssl.conf
    mode: 0644
  notify:
   - reload nginx
  tags:
    - sources_nginx
