---
- name: install certbot
  package: name=certbot

- name: install default.d/letsencrypt.conf
  copy:
    src: default.d/letsencrypt.conf
    dest: /etc/nginx/default.d/letsencrypt.conf
    validate: /usr/local/sbin/ansible-validate-nginx-config %s default.d/letsencrypt.conf
  notify:
   - reload nginx

- name: install conf.d/letsencrypt.conf
  copy:
    src: conf.d/letsencrypt.conf
    dest: /etc/nginx/conf.d/letsencrypt.conf
    validate: /usr/local/sbin/ansible-validate-nginx-config %s conf.d/letsencrypt.conf
  notify:
   - reload nginx

- name: request ssl certificates
  include_tasks: certbot_certonly.yml
  with_items: "{{ certbot_domains }}"
  loop_control:
    loop_var: cert_item

- name: create root SSH keypair for certificate syncing
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    ssh_key_comment: 'root@{{ inventory_hostname }}'
  when:
    - (certbot_domains | length) > 0
    - certbot_certsync_enabled

- name: add SSH known hosts for certificate syncing
  include: ssh_known_hosts.yml
  with_items: '{{ certbot_sync_hosts }}'
  loop_control:
    loop_var: certbot_sync_host
  when:
    - certbot_certsync_enabled

- name: install hook script
  template:
    src: certsync.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/certsync
    mode: 0750
