- name: add Debian backports
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
  when: ansible_distribution == "Debian"

- name: pin flatpak to Debian backports
  copy:
    src: apt-preferences-flatpak-backport
    dest: /etc/apt/preferences.d/flatpak-backport
  when: ansible_distribution == "Debian"

- name: add Ubuntu PPAs
  apt_repository:
    repo: "{{ item }}"
  with_items:
   - "ppa:alexlarsson/flatpak"
   - "ppa:git-core/ppa"
  when: ansible_distribution == "Ubuntu"

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  tags:
   - update

- name: install base packages
  package:
    name: "{{ base_packages + base_packages_deb }}"

- name: apt safe-upgrade
  apt: upgrade=safe
  tags:
   - update
