- name: create admin users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.realname }}"
    groups: "{{ base_admin_group }}"
  with_items: "{{ base_admin_users }}"
  tags:
   - users

# TODO: Get Alex to use a 4k RSA key
- name: add admin ssh keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'ssh/{{ item.username }}.pub') }}"
  with_items: "{{ base_admin_users }}"
  tags:
   - users

- name: allow passwordless sudo
  lineinfile:
    name: /etc/sudoers
    state: present
    regexp: '^%{{ base_admin_group }}(\s+)ALL='
    line: '%{{ base_admin_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: configure deb system
  include: deb.yml
  when: ansible_os_family == "Debian"

- name: configure rpm system
  include: rpm.yml
  when: ansible_os_family == "RedHat"

- name: set timezone to UTC
  timezone:
    name: UTC

- name: configure etckeeper
  template:
    src: etckeeper.conf.j2
    dest: /etc/etckeeper/etckeeper.conf

- name: enable time service
  service:
    name: "{{ base_time_service_unit }}"
    state: started
    enabled: yes

- name: enable node exporter service
  service:
    name: "{{ base_node_exporter_service_unit }}"
    state: started
    enabled: yes

- name: configure native flathub.org hosts
  include: native.yml
  when: base_native

- name: configure Mythic Beasts hosts
  include: mythic.yml
  when: ('mythic' in group_names)
  tags:
   - mythic
