---
- name: install SELinux packages
  package: name=selinux-policy,selinux-policy-targeted
  register: selinux_packages
  when: ansible_os_family == "RedHat"

- name: create autorelabel file
  file: path=/.autorelabel state=touch
  when: selinux_packages.changed
  register: autorelabel

- name: reboot {{ inventory_hostname }} to force selinux relabel
  reboot:
  when: autorelabel.changed

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  tags: selinux
  when: ansible_os_family == "RedHat"
