# TODO: Split all deb and rpm intallations into their own roles
- name: install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
  tags:
   - update

- name: add git-maint COPR
  copy:
    src: group_git-maint-git-epel-7.repo
    dest: /etc/yum.repos.d/group_git-maint-git-epel-7.repo
  when: ansible_distribution == "CentOS"
  tags:
   - update

- name: Enable flatpak copr
  yum_repository:
    name: amigadave-flatpak-epel7
    description: Copr repo for flatpak-epel7 owned by amigadave
    baseurl: https://copr-be.cloud.fedoraproject.org/results/amigadave/flatpak-epel7/epel-7-$basearch/
    gpgcheck: yes
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/amigadave/flatpak-epel7/pubkey.gpg
  when: ansible_distribution == "CentOS"
  tags:
    - update

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
   - update

- name: install base packages
  package:
    name: "{{ base_packages + base_packages_rpm }}"

- name: allow ZeroTier through firewall
  firewalld:
    port: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
   - 9993/udp
   - 9993/tcp
  tags:
    - firewalld

- name: add VPN addresses to firewalld dmz zone
  firewalld:
    zone: dmz
    source: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  with_items: "{{ base_firewall_dmz_sources }}"
  tags:
    - firewalld
