---
- name: include OS-specific variables (Ubuntu).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'

- name: install postgres
  package: name={{ postgresql_packages }} state=latest
  tags:
    - packages

- name: initialize postgres
  become: yes
  become_user: postgres
  become_method: su
  command: "{{ postgresql_bin_path }}/initdb --locale en_US.UTF-8 -E UTF8 -D {{ postgresql_data_dir }}"
  args:
    chdir: "{{ postgresql_data_dir }}"
    creates: "{{ postgresql_config_path }}/postgresql.conf"

- name: enable and start postgres
  systemd:
    name: postgresql
    daemon_reload: yes
    enabled: yes
    state: started
